runtime: python37
# env: flex
# entrypoint: gunicorn -b :$PORT api:app
runtime_config:
  python_version: 3.7

handlers:
- url: /static/js/(.*)
  static_files: build/static/js/\1
  upload: build/static/js/(.*)
- url: /static/css/(.*)
  static_files: build/static/css/\1
  upload: build/static/css/(.*)
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto